apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgresql
  template:
    metadata:
      labels:
        service: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:10
        env:
        - name: POSTGRES_PASSWORD
          value: "student123"
        - name: POSTGRES_DB
          value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    service: postgresql